### ISSUE TITLE
菜單服務

### ISSUE THREAD

**Issue by BlueT** [MOLi-rocks/MOLi-TelegramBot#2]
/menu@MOLiRocks_bot 山雞肉飯

**Comment by zxp86021** [comment]
有請 Foodietrip 組開 api 給我接了(？

**Comment by zxp86021** [comment]
@passerbyid 表示：請直接安裝 Foodietrip

**Comment by passerbyid** [comment]
應該說，這應該屬於 FoodieTrip Bot 的功能。

**Comment by BlueT** [comment]
@passerbyid  那 FoodieTrip Bot 何時要出來？ XD
