### ISSUE TITLE
status command 改接 rpos server

### ISSUE THREAD

**Issue by zxp86021** [MOLi-rocks/MOLi-TelegramBot#4]
Command 改拿 rpos的截圖，節省等待攝影機轉向的時間

**Comment by BlueT** [comment]
之前看 RPOS 一直有截圖存至 /Dec/shm 相關的失敗訊息。
@zxp86021 有測成功過嗎？

**Comment by zxp86021** [comment]
@BlueT 還沒測，先弄 ChuCooDoor 那邊

**Comment by zxp86021** [comment]
Done~使用和融大大貢獻的 snapshot code 完成 rpos snapshot
