### ISSUE TITLE
接電磁鎖的 status api

### ISSUE THREAD

**Issue by ast850328** [MOLi-rocks/MOLi-TelegramBot#6]
GET `/status`
## close:
```json
{
"status": 1,
"message": "MOLi is close now Φ౪Φ."
}
```

## open:
```json
{
"status": 0,
"message": "MOLi is open now (=^-ω-^=)."
}
```

**Comment by zxp86021** [comment]
來了～ https://github.com/MOLi-rocks/MOLi-TelegramBot/commit/a91d7c9787b7f4d277e03aa721e3eaa93d094d69

請使用 `/MagneticLockStatus`，不過好像在 message 裡面有一個 telegram 顯示不出來的奇怪字元
